name: Actions workflow

on:
  # repository_dispatch:
  #   types: [build]
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
  push:
    branches:
      - master
      - 'features/*' # matches anything that starts with feature -- feature/featA, doesn't match feature/feat/a
      - 'features/**' # matches any string after feature/
      - '!feature/featC' # ignore this branch
    tags:
      - v1.*
    paths:
      - '**.js'

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"

      - name: checkout
        uses: actions/checkout@v1

      - name: List files after checkout
        run: |
          pwd
          ls -a

      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: John and Judith

      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"